name: bincheck

on:
  push:
    tags: [ v* ]

permissions:
  contents: read

jobs:

  darwin:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - run: cd build/release/bincheck && ./test-macos ${{ github.ref_name }} ${{ github.sha }}

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - run: cd build/release/bincheck && bash test-windows ${{ github.ref_name }} ${{ github.sha }}
